/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  webboapiSidebar: [
    {
      type: 'autogenerated',
      dirName: '.', // Generates sidebar from the webboapi folder
    },
  ],
};

export default sidebars;
