backend:
  name: gitlab
  repo: "ashersamuel/raptor_documentations"
  branch: "main"
  auth_type: implicit
  app_id: "5d0be88258b439be9f484fa18cbd9c2c849c32c39db6dfd5b7f489c63075c9e7"
  auth_endpoint: "https://gitlab.raptorpos.com/oauth/authorize"

media_folder: "static/img/uploads"
public_folder: "/img/uploads"

collections:
  - name: "docs"
    label: "Docs"
    label_singular: "Doc"
    folder: "docs"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Content", name: "body", widget: "markdown" }
