backend:
  name: github
  branch: main
  repo: Ashersam/raptor_documentations

media_folder: "static/img" # Media files will be stored in the repo under static/images/uploads
public_folder: "/img/" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: blog
    label: "Blog"
    folder: "blog"
    identifier_field: title
    extension: "md"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields:
      - { name: title, label: Title, widget: string }
      - { name: body, label: Body, widget: markdown }
      - { name: slug, label: Slug, widget: string }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Authors", name: "authors", widget: "list", fields: [
            { name: name, label: Name, widget: string },
            { name: title, label: Title, widget: string },
            { name: url, label: URL, widget: string },
            { name: imageUrl, label: Image URL, widget: string }
        ] }

  - name: docs
    label: "Documentation"
    folder: "docs"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list" }

